### ISSUE TITLE
[HOWTO] fix HiddifyDesktop on AppleSilicon Devices

### ISSUE THREAD

**Issue by zargooshifar** [hiddify/HiddifyClashDesktop#18]
سلام
متاسفانه ریلیزی برای مکبوک های دارای AppleSilicon ارائه نشده و نرم افزار اررور میده
برای حل این مشکل از [این آدرس](https://github.com/MetaCubeX/Clash.Meta/releases) فایل clash.meta-darwin-arm64 رو دانلود کنید.
فایل دانلود شده رو اکسترکت کنید. تغییر نام بدید به clash-meta و با ترمیتال دستور زیر رو روش اجرا کنید:
`chmod +x clash-meta`
روی نرم افزار هیدیفای دسکتاپ راست کلیک کنید >show package content > فایلی که دانلود کرده بودید رو تو مسیر contents\MacOS کپی کنید.

**Comment by alifzl** [comment]
سلام
دقيقا من هم همین مشکل رو دارم.

**Comment by alifzl** [comment]
@zargooshifar thanks for the feedback. issue is addressed.
